version: '3'

services:
  financial_data_reader:
    image: opa/financial_data_reader
    build:
      context: .
      dockerfile: ./financial_data_reader.Dockerfile
    depends_on:
      - database
    environment:
      USE_HTTP_CACHE: True
    secrets:
      - fmp_cloud_api_key
      - mongodb_username
      - mongodb_password

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    secrets:
      - mongodb_username
      - mongodb_password

  data_report:
    image: opa/data_report
    build:
      context: .
      dockerfile: ./data_report.Dockerfile
    ports:
      - 8050:8050
    environment:
      HOST: 0.0.0.0
    depends_on:
      - database
    secrets:
      - mongodb_username
      - mongodb_password

  internal_api:
    image: alpine
    command: echo "Hello from internal API"
    depends_on:
      - database

  machine_learning:
    image: alpine
    command: echo "Hello from machine learning"

secrets:
  fmp_cloud_api_key:
    file: secrets/fmp_cloud_api_key
  mongodb_username:
    file: secrets/mongodb_username
  mongodb_password:
    file: secrets/mongodb_password
