version: '3'

services:
  financial_data_reader:
    image: opa/financial_data_reader
    build:
      context: .
      dockerfile: ./financial_data_reader.Dockerfile
    secrets:
      - fmp_cloud_api_key

  database:
    image: alpine
    command: echo "Hello from database"

  data_report:
    image: alpine
    command: echo "Hello from data report"

  internal_api:
    image: alpine
    command: echo "Hello from internal API"

  machine_learning:
    image: alpine
    command: echo "Hello from machine learning"

secrets:
  fmp_cloud_api_key:
    file: secrets/fmp_cloud_api_key
