version: '3'

x-environment: &environment
  LOGURU_LEVEL: INFO
  SETTINGS_FILE_FOR_DYNACONF: /etc/opa/settings.toml
  OPA_SECRETS_DIR: /run/secrets
  OPA_HTTP_CACHE_DIR: /var/http_cache
  OPA_MONGO_HOST: database
  OPA_MONGO_DATABASE: ${OPA_MONGO_DATABASE:-stock_market-dev}

services:
  financial_data_reader:
    image: opa/financial_data_reader
    build:
      context: .
      dockerfile: ./pdm.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=storage,financial_reader
    command: [ "python", "-m", "opa.financial_data_reader" ]
    # With a ~5s database query timeout, the reader will crash on a cold startup (while the
    # database is still initializing).
    # TODO: Investigate if it's a proper solution.
    restart: on-failure
    depends_on:
      - database
    environment:
      <<: *environment
      OPA_USE_HTTP_CACHE: True
    volumes:
      - http-cache:/var/http_cache
    secrets:
      - fmp_cloud_api_key
      - mongodb_username
      - mongodb_password

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db
    secrets:
      - mongodb_root_username
      - mongodb_root_password
      - mongodb_username
      - mongodb_password

  data_report:
    image: opa/data_report
    build:
      context: .
      dockerfile: ./pdm.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=storage,data_report
    command: [ "python", "-m", "opa.data_report" ]
    ports:
      - 8050:8050
    environment:
      <<: *environment
      HOST: 0.0.0.0
    depends_on:
      - database
    secrets:
      - mongodb_username
      - mongodb_password

  internal_api:
    image: opa/api
    build:
      context: .
      dockerfile: ./pdm.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=storage,api
    command: [ "uvicorn", "opa.api:app", "--host", "0.0.0.0", "--port", "8000"]
    environment: *environment
    ports:
      - 8000:8000
    depends_on:
      - database
    secrets:
      - mongodb_username
      - mongodb_password

  test_unit:
    image: opa/test_unit
    build:
      context: .
      dockerfile: ./tests.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=test
    command: [ "pdm", "run", "pytest", "-rfE", "tests/unit" ]
    environment: *environment
    profiles:
      - test

  test_functional:
    image: opa/test_functional
    build:
      context: .
      dockerfile: ./tests.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=test,tests_functional
    command: [ "pdm", "run", "pytest", "-rfE", "tests/functional" ]
    environment: *environment
    depends_on:
      - internal_api
    profiles:
      - test

  test_integration:
    image: opa/test_integration
    build:
      context: .
      dockerfile: ./tests.Dockerfile
      args:
        - OPTIONAL_DEPENDENCIES_GROUPS=test,storage
    command: [ "pdm", "run", "pytest", "-rfE", "tests/integration" ]
    environment:
      <<: *environment
      OPA_MONGO_DATABASE: stock_market-test
    depends_on:
      - database
    profiles:
      - test
    secrets:
      - mongodb_username
      - mongodb_password

  machine_learning:
    image: alpine
    command: echo "Hello from machine learning"

secrets:
  fmp_cloud_api_key:
    file: app_data/secrets/fmp_cloud_api_key
  mongodb_root_username:
    file: app_data/secrets/mongodb_root_username
  mongodb_root_password:
    file: app_data/secrets/mongodb_root_password
  mongodb_username:
    file: app_data/secrets/mongodb_username
  mongodb_password:
    file: app_data/secrets/mongodb_password

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app_data/db'

  http-cache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app_data/http_cache'
