[default]
use_http_cache = false
secrets_dir = "app_data/secrets"
http_cache_dir = "app_data/http_cache"
mongo_host = "localhost"
mongo_database = "stock_market-dev"
api_host = "localhost"
data_report_host = "localhost"
data_report_port = "8050"
