== Data storage

=== Scope

From <<_financial_data_retrieval>>, we now have a good grasp of the kind of data we will be handling within this project. So far we have only been retrieving it via an external API, and it would be very impractical to keep on doing so.

It is cumbersome indeed to rely on HTTP requests to an external provider. It is extremely slow, and the number of requests we can issue is limited. Chances are we will often be requesting the exact same sets of data. And last but not least, we have no way to organize and query the data to extract the patterns we might be looking for in a machine learning model or simply for data visualisation.

A better approach would be to retrieve all the data we might need by emitting those API requests once and for all and storing the data contained in their response in an organized way ; we could update it when necessary.

Any automated tool or data scientist that may need that data will now use that cache.

=== Constraints

We have seen that the financial data we aim to retrieve is always shaped basically in the same way, whether it is historical or streaming data. Some fields are not always present, though.

[#python-stock-value-class-2]
.Definition of an abstract StockValue class
[,python]
// This should display the definition of StockValue class
----
include::../opa/core/financial_data.py[lines=14..21]
----

Though they is no numerical ID, short strings named "tickers" or "symbols" in stock market jargon are used to identify a given stock on a stock marketfootnote:[https://en.wikipedia.org/wiki/Ticker_symbol] ; they are unique by design and can therefore be safely used to identify a given company.

The data does not exhibit any complex relationship patterns either. There is a 1-to-n relationship between companies and stock values. And any other additional information we might need in the future will likely be related to the company as well.

Being the measurement of a stock value at a given moment, the data is intrinsically time-related and exhibit all the characteristics of time-series data.

There is no hard constraint in terms of data consistency or durability. The stored data will be merely a cache of the data available in external APIs, and therefore not critical in any sense. No original data is ever produced by our applications ; in the worst case the data is still available from the APIs and one can always retrieve from them.

In terms of data access patterns, the values stored in the database will be written to only once (when it is retrieved from the API) and read many times.

=== Choice of a database

So many database options exist that we will first restrict our choice by choosing among the various types of databases, that is :

. Relational
. Graph-oriented
. Column-oriented
. Key-value
. Document-oriented

The choice here is that of a design philosophy, since the lines are quite blurred between the different categories ; e.g. almost all SQL databases have a very good support of JSON, making them very capable as "document-oriented" databases.

As we have seen, the data we'll be handling has very few relational properties. A fully-fledged SQL relational database is therefore not the favored option. It does not exhibit any interesting graph properties either, rendering a graph-oriented database useless. 

Column-oriented databases are more of an option for e.g. OnLine Analytical Processing of data with complex relationships, which is not the case here.

Key-value databases trade expressiveness in data structure / query for very high performance. They might be a reasonable option given the simple structure of our data.

Overall, though, we do not really need that very high performance, and we'll be happy to trade a bit of performance for the light data structuring that document-oriented databases offers. We might also need the expressiveness they allow in terms of query / aggregations / ...

A document-oriented datastore therefore appears like a good choice. MongoDBfootnote:[https://www.mongodb.com/] is the most popular implementation of such a database. It supports time-series collectionsfootnote:[https://www.mongodb.com/docs/v6.0/core/timeseries-collections/] of which stock prices are a prime example. It also features schema validationfootnote:[https://www.mongodb.com/docs/manual/core/schema-validation/] to ensure that the documents we insert are in an expected format.

=== Implementation

Should we change our mind regarding the database choice, we'll keep some flexibility by defining a `Storage` class with an API that will abstract away the concrete implementation of the database.

[#python-storage-abstract-class]
.Definition of an abstract Storage class
[,python]
// This should display the definition of Storage class
----
include::../opa/core/storage.py[lines=6..27]
----

The layout of the MongoDB database itself will be setup using the approach recommended of the MongoDB Docker image's pagefootnote:["Initializing a fresh instance" paragraph on https://hub.docker.com/_/mongo], via a `mongo-init.js` file executed on the first startup.

We will define as many collections as we have different kinds of data ; one for historical stock values, one for streaming/recent stock values, one for additional company information, ...

Each of these collections has a unique index to ensure that no data is duplicated.

[#definition-of-unique-indexes]
.Definition of unique indexes
[,js]
// This should display the calls do db.collection.createIndex(...)
----
include::../mongo-init.js[lines=60..61]
----

We also leverage MongoDB's schema validation feature to ensure that the inserted data always matches a well-defined set of rules defined from the data format exposed in <<stock-value-record-fields>>. Those rules include ensuring that some fields are ALWAYS present (`ticker`, `date` and `close` values) ; and that fields should have the expected type (mostly `double`, with some `date` or `int`).

[#definition-of-constraints]
.Definition of constraints
[,js]
// This should display the json-schema used for validation of historical values
----
include::../mongo-init.js[lines=17..27]
                ...
include::../mongo-init.js[lines=32..35]
                ...
include::../mongo-init.js[lines=48..55]
----

////
Error handling
Performance measurement
////
