== Financial data retrieval

=== Scope

Within this project, we will be looking at the evolution of stock market values of several companies.

In an ideal world, the ultimate goal would be to store as much fine-grained data  for as large a period of time as possible ; this would allow for much finer tuning of any Machine Learning model we would train. But this is costly both in terms of data storage and CPU usage and is considered out of scope.

We will therefore restrain our focus on two kinds of data within this project :

"historical" data::
    * spans long periods of time
    * adjusted and corrected afterwardsfootnote:[https://www.investopedia.com/terms/a/adjusted_closing_price.asp]
    * quite coarsed-grained (one data point every few hours / every day)
"streaming" data::
    * very recent (can be retrieved almost in real time)
    * usually quite fine-grained (one data point every few minutes)

=== API provider choice

Dozens of API providers exist for stock market data. Some of them are geared towards profesionnals and provide very fine data over long ranges of time. Access to real-time / slightly delayed data is also of prime value and usually requires proper licensing from the stock exchange authoritiesfootnote:[https://www.alphavantage.co/realtime_data_policy/].

In the relatively basic scope of this project, we have been focusing on some providers that allow a free access to their API. All of them are mainly aimed at US markets.

====
[#stock-market-providers]
.Some stock market data providers
MarketStack:: https://marketstack.com/
Alphavantage:: https://www.alphavantage.co/
EODHD:: https://eodhistoricaldata.com/
FMP Cloud:: https://fmpcloud.io/
Yahoo Finance:: The official Yahoo Finance API seems to have been discontinued but it is still working and its API can be retro-engineered from e.g. this unofficial Python client : https://github.com/ranaroussi/yfinance
====

In terms of the kind of stock market data they give access to, they are virtually identical. The main differences lie in the limits they set on request rate and the information they require for registration and retrieval of an API key. The table below sums up their main differences.

[#comparison-table]
.Comparison of stock Market data providers
[%autowidth]
|===
|Company |Registration |API limits |API documentation

s|MarketStack
|Email + name + phone
|100 requests/month
|Yes

s|Alphavantage
|Email
|5 requests / minute, 500 requests / day
|Yes

s|Yahoo Finance
|No
|Unrestricted in practice
|No

s|EODHD
|Google OR Github OR email + name
|20 requests / day
|Yes

s|FMP Cloud
|Google OAuth2 OR email/password
|250 requests / day
|Yes
|===

Once the project is developed and released in production, a few requests per day (one per company we track) should be enough. This already rules out MarketStack, which is too restricted.

In the development phase though, we'll be making request to the APIs much more often than that, and hitting the API rate should not be a blocking issue. This rules out EODHD and its maximum of 20 requests per day.

Yahoo Finance does not have a proper API documentation and is almost too easy to use with the unofficial Python client `yfinance`.

This leaves us with Alphavantage or FMP Cloud.

=== Examples of data

:url_fmpcloud_deep_history: https://fmpcloud.io/api/v3/historical-price-full/AAPL?serietype=line&apikey=fmp_secret_key
:url_fmpcloud_detailed_history: https://fmpcloud.io/api/v3/historical-price-full/AAPL?apikey=fmp_secret_key
:url_fmpcloud_streaming: https://fmpcloud.io/api/v3/historical-chart/15min/AAPL?apikey=fmp_secret_key
:url_alphavantage_full_history: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=AAPL&apikey=alpha_secret_key
:url_alphavantage_streaming: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&interval=15min&symbol=AAPL&apikey=alpha_secret_key

Once in possession of an API key, retrieving data from those providers is done via a simple `GET` request on the appropriate endpoint. The tickerfootnote:[The ticker is a short string used to uniquely identify a company on stock markets ; e.g. Microsoft is MSFT, Intel is INTC, ... In this report, examples will be using the ticker AAPL (for Apple)] is set either in some part of the URL path (e.g. {url_fmpcloud_streaming}), or as a query string parameter (e.g. {url_alphavantage_streaming}). The body of the server response contains the data encoded in JSON format.

Below are 4 examples of data mainly retrieved from FMP Cloud, retaining only some records for brievety (a typical response contains hundreds to thousands of records).

* <<deep-history-fmp, deep historical data>> that spans about 40 years but with little detail
* <<detailed-history-fmp, detailed historical data>> that spans only a few years but with great detail
* <<streaming-fmp, streaming data>>
* <<streaming-alphavantage, streaming data from Alphavantage>>, for comparison

[#deep-history-fmp]
.FMPCloud deep historical datafootnote:[Retrieved from {url_fmpcloud_deep_history}]
[,json]
----
{
    "historical": [
        {
            "close": 190.69,
            "date": "2023-07-14"
        },
        {
            "close": 190.54,
            "date": "2023-07-13"
        },
        ...
        {
            "close": 0.12165,
            "date": "1980-12-15"
        },
        {
            "close": 0.12835,
            "date": "1980-12-12"
        }
    ],
    "symbol": "AAPL"
}
----

[#detailed-history-fmp]
.FMP Cloud detailed historical datafootnote:[Retrieved from {url_fmpcloud_detailed_history}]
[,json]
----
{
    "historical": [
        {
            "adjClose": 190.690002,
            "change": 0.46,
            "changeOverTime": 0.0024181,
            "changePercent": 0.24181,
            "close": 190.69,
            "date": "2023-07-14",
            "high": 191.1799,
            "label": "July 14, 23",
            "low": 189.63,
            "open": 190.23,
            "unadjustedVolume": 40764621,
            "volume": 40835691,
            "vwap": 190.46
        },
        {
            "adjClose": 190.539993,
            "change": 0.04,
            "changeOverTime": 0.0002099738,
            "changePercent": 0.02099738,
            "close": 190.54,
            "date": "2023-07-13",
            "high": 191.19,
            "label": "July 13,23",
            "low": 189.78,
            "open": 190.5,
            "unadjustedVolume": 41342300,
            "volume": 41337338,
            "vwap": 190.57
        }
    ],
    "symbol": "AAPL"
}
----

[#streaming-fmp]
.FMP Cloud streaming datafootnote:[Retrieved from: {url_fmpcloud_streaming}]
[,json]
----
[
    {
        "close": 190.69,
        "date": "2023-07-14 16:00:00",
        "high": 190.71,
        "low": 190.3978,
        "open": 190.69,
        "volume": 1654688
    },
    {
        "close": 190.72,
        "date": "2023-07-14 15:45:00",
        "high": 190.74,
        "low": 190.26,
        "open": 190.42,
        "volume": 3749214
    },
    {
        "close": 190.415,
        "date": "2023-07-14 15:30:00",
        "high": 190.49,
        "low": 190.16,
        "open": 190.275,
        "volume": 1254758
    },
    {
        "close": 190.275,
        "date": "2023-07-14 15:15:00",
        "high": 190.42,
        "low": 190.04,
        "open": 190.04,
        "volume": 1315560
    }
]
----

[#streaming-alpha]
.Alphavantage streaming datafootnote:[Retrieved from: {url_alphavantage_streaming}]
[,json]
----
{
    "Meta Data": {
        "1. Information": "Intraday (15min) open, high, low, close prices and volume",
        "2. Symbol": "AAPL",
        "3. Last Refreshed": "2023-07-14 19:45:00",
        "4. Interval": "15min",
        "5. Output Size": "Compact",
        "6. Time Zone": "US/Eastern"
    },
    "Time Series (15min)": {
        "2023-07-14 19:15:00": {
            "1. open": "190.8000",
            "2. high": "190.8100",
            "3. low": "190.7500",
            "4. close": "190.7600",
            "5. volume": "2896"
        },
        "2023-07-14 19:30:00": {
            "1. open": "190.7600",
            "2. high": "190.7600",
            "3. low": "190.7000",
            "4. close": "190.7100",
            "5. volume": "2211"
        },
        "2023-07-14 19:45:00": {
            "1. open": "190.7300",
            "2. high": "190.7500",
            "3. low": "190.6900",
            "4. close": "190.7200",
            "5. volume": "11717"
        }
    }
}
----

From those examples we can observe that both historical and streaming data from any provider follow the same schema. They define _units of time_ over which some values are given. 

A given data record will always contain at least the following elements :

Date:: The moment in time for which the values are provided
Interval length:: The duration over which those values are computed (15 minutes, 24 hours, ...)
Close:: The value at the end of the unit of time

And they will optionally contain the following additional elements :

Open:: The value at the start of the unit of time
Low:: The lowest value over the unit of time
High:: The highest value over the unit of time
Volume:: The number of stocks exchanged over the unit of time

In terms of data format, the _date_ is (or can be trivially converted to) a `datetime`. The interval length can be represented as a number of minutes expressed in `int`. The _close_, _open_, _low_, _high_ values are prices in dollars, of type `float`. The volume is an `int`.

[%autowidth]
|===
|Value |Type |Optional?

|date
|`datetime`
|no

|interval
|`int`
|no

|close
|`float`
|no

|open
|`float`
|yes

|high
|`float`
|yes

|low
|`float`
|yes

|volume
|`int`
|yes
|===

=== Data representation

Now that we have a better understanding of the kind of data we will be handling, we can define a generic class to represent both historical and streaming stock value.

[#python-stock-value-definition]
.Definition of StockValue class
[,python]
----
include::../opa/core/financial_data.py[lines=8..15]
----

=== Access to providers' data

An abstract class is defined to retrieve data from a provider, with a method that can get either streaming or historical data.

[#python-stock-market-provider-definition]
.Definition of StockMarketProvider abstract class
[,python]
----
include::../opa/core/providers.py[lines=6..12]
----

The implementation of the class that gets data from FMP Cloud provider can be found in link:../opa/providers/fmp_cloud.py[fmp_cloud.py].

==== Data validation

To ensure that the data we get from the APIs is in a format that we expect, we use the `pydantic` libraryfootnote:[https://docs.pydantic.dev/2.0/] to define some models of the data.

[,python]
----
include::../opa/providers/fmp_cloud.py[lines=10..12;19..33]
----

Validation of the server's response can now be done by simply instantiating one of those classes with e.g. [,python]`FmpCloudHistoricalData(**json)`.

==== Handling of secret API keys

The API keys are confidential and extra-care must be taken to not leak them into version control or hardcode them.

A `get_secret` function has been added in a link:../opa/env.py[env.py] module to handle those secrets. It relies either on the existence of a `./secrets` directory at the root of the projet (that should be created on the local clone of the repo) or a `/secrets` directory created by Docker Secrets.
