name: Unit tests

on: push

jobs:
  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: "3.11"

    - name: Install package in test mode
      run: pip install .[test]

    - name: Run tests
      run: |
        pytest tests/unit
